/**
 * @codemirror/lang-typst
 *
 * Full CodeMirror 6 language support for Typst.
 *
 * Usage:
 *   import { typst } from "@codemirror/lang-typst";
 *   new EditorView({ extensions: [typst()] })
 */

import { LRLanguage, LanguageSupport, indentNodeProp, foldNodeProp, foldInside } from "@codemirror/language";
import { styleTags, tags as t } from "@lezer/highlight";
import { completeFromList, CompletionContext } from "@codemirror/autocomplete";
import { parser as typstParser } from "./parser.js"; // generated by lezer-generator

// ─── Highlight tags ────────────────────────────────────────────────────────
//
// We map every Typst node type to a standard Lezer highlight tag so that
// any CodeMirror theme (One Dark, GitHub Light, etc.) works out-of-the-box.

const typstHighlighting = styleTags({

    // ── Comments ──────────────────────────────────────────────────────────────
    "LineComment BlockComment": t.comment,
    "shebang": t.lineComment,

    // ── Markup structural elements ────────────────────────────────────────────
    "HeadingMarker": t.heading,
    "Heading/HeadingMarker": t.heading1,

    "Strong/Star": t.strong,
    "Strong": t.strong,
    "Emph/Underscore": t.emphasis,
    "Emph": t.emphasis,

    "ListMarker": t.list,
    "EnumMarker": t.list,
    "TermMarker": t.list,
    "TermItem/Colon": t.list,

    "Label": t.labelName,
    "RefMarker": t.labelName,
    "Link": t.url,

    "Escape": t.escape,
    "Shorthand": t.escape,
    "Linebreak": t.escape,
    "SmartQuote": t.string,

    // Raw blocks
    "Raw": t.monospace,
    "Raw/RawDelim": t.processingInstruction,
    "Raw/RawLang": t.labelName,
    "Raw/Text": t.monospace,

    // ── Math ─────────────────────────────────────────────────────────────────
    "Equation/Dollar": t.processingInstruction,
    "MathIdent": t.variableName,
    "MathText": t.number,
    "MathShorthand": t.operator,
    "MathAlignPoint": t.operator,
    "MathPrimes": t.operator,
    "MathRoot Root": t.operator,
    "Hat Underscore": t.operator,
    "MathFrac/Slash": t.operator,
    "MathAttach": t.operator,
    "MathDelimited/MathOpen MathDelimited/MathClose": t.bracket,

    // ── Code keywords ─────────────────────────────────────────────────────────
    "Let Set Show Context If Else For While Break Continue Return Import Include As": t.keyword,
    "Not And Or In": t.operatorKeyword,
    "None": t.null,
    "Auto": t.atom,

    // ── Code operators ────────────────────────────────────────────────────────
    "Plus Minus Star Slash": t.operator,
    "EqEq ExclEq Lt LtEq Gt GtEq": t.compareOperator,
    "Eq PlusEq HyphEq StarEq SlashEq": t.updateOperator,
    "Dots": t.operator,
    "Arrow": t.punctuation,
    "Hash": t.meta,

    // ── Delimiters ────────────────────────────────────────────────────────────
    "LeftBrace RightBrace": t.brace,
    "LeftBracket RightBracket": t.squareBracket,
    "LeftParen RightParen": t.paren,
    "Comma Semicolon": t.punctuation,
    "Dot Colon": t.punctuation,

    // ── Literals ──────────────────────────────────────────────────────────────
    "Bool": t.bool,
    "Int Float Numeric": t.number,
    "Str": t.string,

    // ── Identifiers ───────────────────────────────────────────────────────────
    "Ident": t.variableName,
    "FuncCall/Ident": t.function(t.variableName),
    "FuncCall/primary/Ident": t.function(t.variableName),
    "LetBinding/Ident": t.definition(t.variableName),
    "Params/Ident": t.definition(t.variableName),
    "ForLoop/Ident": t.definition(t.variableName),

    "FieldAccess/Ident": t.propertyName,
    "Named/Ident": t.propertyName,

    // ── Dollar in code (inline equation) ─────────────────────────────────────
    "Dollar": t.processingInstruction,
});

// ─── Fold support ─────────────────────────────────────────────────────────────
//
// Folds for all block-like structures.

const typstFolding = foldNodeProp.add({
    // Code blocks and content blocks
    CodeBlock(node) {
        return foldInside(node);
    },
    ContentBlock(node) {
        return foldInside(node);
    },
    // Parenthesized expressions (arrays, dicts, args, params)
    Parens(node) {
        return foldInside(node);
    },
    // Block comments
    BlockComment(node) {
        return { from: node.from + 2, to: node.to - 2 };
    },
    // Equations (multiline)
    Equation(node) {
        return foldInside(node);
    },
});

// ─── Auto-indent support ──────────────────────────────────────────────────────

const typstIndent = indentNodeProp.add({
    CodeBlock(context) {
        return context.baseIndent + context.unit;
    },
    ContentBlock(context) {
        return context.baseIndent + context.unit;
    },
    Parens(context) {
        return context.baseIndent + context.unit;
    },
});

// ─── Language definition ─────────────────────────────────────────────────────

export const typstLanguage = LRLanguage.define({
    name: "typst",
    parser: typstParser.configure({
        props: [
            typstHighlighting,
            typstFolding,
            typstIndent,
        ],
    }),
    languageData: {
        commentTokens: { line: "//", block: { open: "/*", close: "*/" } },
        // Auto-close pairs
        closeBrackets: {
            brackets: ["(", "[", "{", '"', "$"],
            // Content block
            before: ")]}$",
        },
        indentOnInput: /^\s*[}\])]$/,
    },
});

// ─── Autocomplete ─────────────────────────────────────────────────────────────
//
// Provides completions for:
//  - Typst keywords
//  - Common built-in functions / identifiers
//  - Math symbols (when inside an equation)

const keywordCompletions = [
    "let", "set", "show", "context", "if", "else", "for", "in",
    "while", "break", "continue", "return", "import", "include", "as",
    "none", "auto", "true", "false", "not", "and", "or",
].map(kw => ({ label: kw, type: "keyword" }));

const builtinFunctionCompletions = [
    // Typst standard library selection
    "text", "par", "h", "v", "box", "block", "grid", "table", "image",
    "figure", "footnote", "cite", "bibliography", "pagebreak", "colbreak",
    "rect", "circle", "ellipse", "line", "path", "polygon",
    "emph", "strong", "underline", "overline", "strike",
    "sub", "super", "smallcaps",
    "link", "ref",
    "equation", "math",
    "lorem", "datetime",
    "sys.inputs", "document",
    "type", "repr", "assert", "panic", "eval",
    "str", "int", "float", "bool", "bytes", "label", "regex",
    "range", "array", "dictionary",
    "read", "json", "csv", "toml", "yaml", "xml",
].map(fn => ({ label: fn, type: "function" }));

const mathSymbolCompletions = [
    // Common LaTeX-like identifiers recognised in math mode
    "alpha", "beta", "gamma", "delta", "epsilon", "zeta", "eta", "theta",
    "iota", "kappa", "lambda", "mu", "nu", "xi", "pi", "rho", "sigma",
    "tau", "upsilon", "phi", "chi", "psi", "omega",
    "Alpha", "Beta", "Gamma", "Delta", "Epsilon", "Zeta", "Eta", "Theta",
    "Lambda", "Pi", "Sigma", "Phi", "Psi", "Omega",
    "sum", "prod", "integral", "oint",
    "infty", "partial",
    "forall", "exists", "nexists",
    "nabla", "laplace",
    "in", "notin", "subset", "supset", "subseteq", "supseteq",
    "union", "inter", "complement",
    "and", "or", "not",
    "approx", "sim", "cong", "equiv", "neq", "leq", "geq",
    "times", "div", "plus.minus", "minus.plus",
    "arrow.r", "arrow.l", "arrow.lr", "arrow.r.long", "arrow.double.r",
    "dots", "dots.v", "dots.c",
    "bold", "italic", "cal", "frak", "bb",
    "floor", "ceil",
    "vec", "mat", "cases",
    "lim", "log", "ln", "exp", "sin", "cos", "tan",
    "arcsin", "arccos", "arctan",
    "sinh", "cosh", "tanh",
    "min", "max", "sup", "inf",
    "det", "dim", "ker", "deg",
].map(sym => ({ label: sym, type: "variable" }));

/**
 * Provides context-aware autocomplete for Typst source files.
 * - Keywords and built-ins anywhere
 * - Math symbols inside equations
 */
function typstCompletions(context: CompletionContext) {
    // Check if we're inside an Equation node for math-specific completions
    const nodeBefore = context.state.doc.sliceString(
        Math.max(0, context.pos - 50),
        context.pos
    );

    // Simple heuristic: are we inside a $ ... $ block?
    const dollarCount = (nodeBefore.match(/\$/g) || []).length;
    const inMath = dollarCount % 2 === 1;

    const word = context.matchBefore(/[\w\-]+/);
    if (!word) return null;
    if (word.from === word.to && !context.explicit) return null;

    const options = inMath
        ? [...mathSymbolCompletions, ...keywordCompletions]
        : [...keywordCompletions, ...builtinFunctionCompletions];

    return {
        from: word.from,
        options,
    };
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Returns a LanguageSupport instance for Typst.
 *
 * @example
 * import { typst } from "@codemirror/lang-typst";
 * new EditorView({ extensions: [typst()] })
 */
export function typst() {
    return new LanguageSupport(typstLanguage, [
        typstLanguage.data.of({ autocomplete: typstCompletions }),
    ]);
}
