// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "[OQOPOOQOOOOO",
  stateData: "V~ORPO~O",
  goto: "QPP",
  nodeNames: "⚠ R",
  maxTerm: 3,
  skippedNodes: [0],
  repeatNodeCount: 0,
  tokenData: "j~RRYZ[#O#P[#Q#R[~aRR~YZ[#O#P[#Q#R[",
  tokenizers: [0],
  topRules: {"R":[0,1]},
  tokenPrec: 0
})
