// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "[OQOPOOQOOOOO",
  stateData: "V~ORPO~O",
  goto: "QPP",
  nodeNames: "⚠ R",
  maxTerm: 3,
  skippedNodes: [0],
  repeatNodeCount: 0,
  tokenData: "!Q~RTq!Qb!Q![g![#sb#t;'Sb<%lOb~gOR~~lQR~!O!Pr!Q![g~uP!Q![x~}PR~!Q![x",
  tokenizers: [0],
  topRules: {"R":[0,1]},
  tokenPrec: 0
})
