// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "[OQOPOOQOOOOO",
  stateData: "V~ORPO~O",
  goto: "QPP",
  nodeNames: "⚠ R",
  maxTerm: 3,
  skippedNodes: [0],
  repeatNodeCount: 0,
  tokenData: "#t~RdYZ!aqr!ars!ast!atu!avw!awx!az{!a!P!Q!a!^!_!a!`!a!a!b!c!a!}#O!a#O#P!a#P#Q!a#Q#R!a#R#S!a#S#T!a#o#p!a#q#r!a~!fdR~YZ!aqr!ars!ast!atu!avw!awx!az{!a!P!Q!a!^!_!a!`!a!a!b!c!a!}#O!a#O#P!a#P#Q!a#Q#R!a#R#S!a#S#T!a#o#p!a#q#r!a",
  tokenizers: [0],
  topRules: {"R":[0,1]},
  tokenPrec: 0
})
